/* DATABASE */
CREATE DATABASE IF NOT EXISTS todosdb DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

/* TABLE TODOS */
CREATE TABLE todos (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(255) NOT NULL,
  is_completed BOOLEAN NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;